services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: runtime
    command: uv run python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
