services:
  nginx:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - nginx_network

networks:
  nginx_network:
    name: "nginx_network"
    external: true